name: Get Bing Wallpaper

on:
  schedule:
    - cron: '0 7 * * *' # 每天下午3点运行 (北京时间)
  push:
    paths:
      - '.github/**' # 监听 .github 文件夹的修改
  workflow_dispatch: # 添加 workflow_dispatch 触发器，手动触发工作流程

jobs:
  get_today_wallpaper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Get Date
      run: |
        echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
        echo "MONTH=$(date +%m)" >> $GITHUB_ENV

    - name: Create folders
      run: |
        mkdir -p "bing/archive/${{ env.YEAR }}/${{ env.MONTH }}"

    - name: Download Today's Bing Wallpaper
      run: |
        IMAGE_URL=$(curl -sL "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US" | jq -r '.images[0].url')
        FULL_IMAGE_URL="https://www.bing.com${IMAGE_URL/1920x1080/UHD}"
        FILENAME=$(date +'%Y%m%d').jpg
        echo "Downloading Bing Wallpaper: $FULL_IMAGE_URL"
        wget -q -O "$FILENAME" "$FULL_IMAGE_URL"
        cp "$FILENAME" "bing/today.jpg"
        mv "$FILENAME" "bing/archive/${{ env.YEAR }}/${{ env.MONTH }}/$FILENAME"
    - name: Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update"
        git push
