name: state

on:
  schedule:
    - cron: '0 7 * * *' # 每天下午3点运行 (北京时间)
  push:
    paths:
      - '.github/**' # 监听 .github 文件夹的修改
  workflow_dispatch: # 添加 workflow_dispatch 触发器，手动触发工作流程

jobs:
  state:
    runs-on: ubuntu-latest

    steps:
    - name: cr
      run: |
        echo "run successfully"