name: Daily Download Xecades Image

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC 0点（北京时间8点）
  workflow_dispatch:

jobs:
  download-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set date variable
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Create xecades directory if not exists
        run: mkdir -p xecades

      - name: Download image
        run: |
          curl -L "https://api.xecades.xyz/api?img=3&luogu=Smacat&bilibili=%E4%BA%94%E5%91%B3%E6%A6%B4%E8%8E%B2&quote=qwq&email=admin%40wanwusangzhi.top&date=2025-9-1&str=+2025+%E6%9A%91%E5%81%87%E5%BC%80%E5%AD%A6" \
          --output "xecades/${DATE}.png"

      - name: Commit and push image
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add xecades/
          git commit -m "chore: add xecades image for ${DATE}" || echo "No changes to commit"
          git push
        env:
          # 需要有workflow权限写入仓库
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
